# Path to your oh-my-zsh installation.
# Unset direnv variables that may come from emacs
unset DIRENV_DIR
unset DIRENV_DIFF
unset DIRENV_WATCHES
unset DIRENV_FILE
unset PYENV_VERSION
unset PYENV_VIRTUALENV_INIT

export ZSH=${HOME}/.oh-my-zsh

# User machine local settings

# Debug
# export ZSH_DEBUG_STARTUP=1
# set -x

export ZSH_USER_LOCAL="$HOME/.local/share/zsh/"
export ZSH_CUSTOM="$ZSH_USER_LOCAL/custom"
if [ -d "$HOME/.local/bin" ] ; then
    export PATH="$HOME/.local/bin:$PATH"
fi

export PATH="$HOME/go/bin:$PATH"

# Chase symlinks and avoid a lot of nonsense
setopt chaselinks

fpath+="$ZSH_CUSTOM/zfunc"

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="frontcube"

# Disable magic quoting of URLs
export DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# customize keybindings
bindkey \^u backward-kill-line

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(gitfast python sudo pyenv fzf direnv)

# User configuration

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

export EDITOR=vi
alias e=$EDITOR

# custom user environment
if [ -f $HOME/.zprofile ] ; then
    source $HOME/.zprofile
fi

# global environment. Should just export variables and aliases
if [ -d ~/.local/etc/env.d/ ]; then
    for env_file in `ls ~/.local/etc/env.d/* | sort` ; do
        [ -n "$ZSH_DEBUG_STARTUP" ] && echo "Loading $env_file"
        source $env_file
    done
fi

# site configuration. Can be used to update plugins
# e.g. plugins+=(dnf systemd)
if [ -f ~/.local/share/zsh/site_conf.zsh ] ; then
    [ -n "$ZSH_DEBUG_STARTUP" ] && echo "Loading ~/.local/share/zsh/site_conf.zsh"
    source ~/.local/share/zsh/site_conf.zsh
fi

# Shell setup
# These scripts are used to initialize interactive aspects of the shell
# and can execute more complex commands, redefine aliases, etc.

# EARLY rc.d
# these can update plugins and set environment variables that may be used by oh-my-zsh
if [ -d ~/.local/etc/rc.d ]; then
    for rc in ~/.local/etc/rc.d/[0-4]*; do
        [ -n "$ZSH_DEBUG_STARTUP" ] && echo "Loading $rc"
        source $rc
    done
fi

# Classic profile
if [ -f ${HOME}/.profile ]; then
   [ -n "$ZSH_DEBUG_STARTUP" ] && echo "Loading ~/.profile"
   source ${HOME}/.profile
   [ -n "$ZSH_DEBUG_STARTUP" ] && echo "Loaded ~/.profile"
fi

[ -n "$ZSH_DEBUG_STARTUP" ] && echo "Loading oh-my-zsh"
source $ZSH/oh-my-zsh.sh
[ -n "$ZSH_DEBUG_STARTUP" ] && echo "Loaded"

# LATE rc.d script
# These files are supposed to execute at the end of startup, after zsh has already been started
if [ -d ~/.local/etc/rc.d ]; then
    for rc in ~/.local/etc/rc.d/[5-9]*; do
        [ -n "$ZSH_DEBUG_STARTUP" ] && echo "Loading $rc"
        source $rc
        [ -n "$ZSH_DEBUG_STARTUP" ] && echo "Loaded $rc"
    done
fi
