#!/usr/bin/env python
# -*- BUNDLEDIRS -*-

# File: "/home/kassick/Sources/dotfiles/install.py"
# Created: "Thu Jul 21 21:46:45 2016"
# Updated: "2018-03-24 18:24:07 kassick"
# $Id$
# Copyright (C) 2016, Rodrigo Kassick

import os
import os.path as path
import sys
import re
import subprocess

DOT_DIR="dots"
BUNDLE_DIR="bundle"
BUNDLEDIRS_DIR="bundle_dirs"
INSTALL_DIR="install"
SELECTION_FILE="dot_select.txt"

def add_dot(dots, name, path, install, bundle, bundledirs):
    if name == '.keep': return #ignore .keep files
    if name in dots:
        dots[name] = tuple(map(lambda i: i[0] if i[1] is None else i[1],
                           zip([path, install, bundle, bundledirs], dots[name])))
    else:
        dots[name] = (path, install, bundle, bundledirs)

def rec_file_split(p):
    if len(p) == 0:
        return []
    elif p == '/':
        return ['/']
    else:
        (h, t) = path.split(p)
        return rec_file_split(h) + [t]


def files_conflict_resolve(src, dst, renames, removes, installs):
    if (os.path.islink(dst)):
        # exists and is a link
        removes.append(dst)
        installs.append(( os.path.abspath( src ), dst) )
    elif os.path.exists(dst):
        # Exists and is not a link
        print "\tFile %s already exists" % dst
        print "\tAction:"
        print "\t\t (o)verride"
        print "\t\t (b)ackup"
        print "\t\t (s)kip"

        action = None
        while not(action in ['o', 'b', 's']):
            action = sys.stdin.readline().strip()

        if action == 'o':
            removes.append(dst)
            installs.append( (os.path.abspath( src ), dst) )
        elif action == 'b':
            renames.append( (dst, dst + '.orig') )
            installs.append( (os.path.abspath( src ), dst) )
        pass
    else:
        installs.append( (os.path.abspath(src), dst) )

def dot_install(dot, dot_path, dot_install, dot_bundle, dot_bundledirs):
    removes = []
    renames = []
    dirs = []
    installs = []
    executes = []

    if dot_path:
        dest = path.expanduser(path.join('~', '.' + dot_path ))
        src = path.join(DOT_DIR, dot_path)

        print "%s --> %s" % (src, dest)

        files_conflict_resolve(src, dest, renames, removes, installs)

    if dot_bundledirs:
        print "Install %s's directory-bundles" %dot

        dirnames = os.listdir(os.path.join(BUNDLEDIRS_DIR, dot))

        for d in dirnames:
            src = os.path.join(BUNDLEDIRS_DIR, dot, d )
            dest = os.path.expanduser(os.path.join("~", "." + d))

            files_conflict_resolve(os.path.abspath(src), dest, renames, removes, installs)

    if dot_bundle:
        print "Install %s's mergeable bundles" % dot
        for root, dirnames, filenames in os.walk(path.join(BUNDLE_DIR, dot)):
            destbase = os.path.sep.join(rec_file_split(root)[2:]) # ditch bundle/dotname

            for d in dirnames:
                do_mkdir = True
                if len(destbase) == 0:
                    dest_dir = os.path.expanduser(os.path.join("~", "." + d))
                else:
                    dest_dir = os.path.expanduser(os.path.join('~', '.' + destbase, d))
                if os.path.exists(dest_dir):
                    if os.path.isdir(dest_dir):
                        do_mkdir = False
                    else:
                        print "\tTarget %s is not a directory" % destk_dir
                        print "\t\t (b)ackup"
                        print "\t\t (i)gnore"
                        action = None
                        while not(action in ['b', 'i']):
                            action = sys.stdin.readline().strip()

                        if action == 'b':
                            os.rename(dest_dir, dest_dir + ".orig")
                        else:
                            do_mkdir = False
                        pass
                    pass

                if do_mkdir:
                    dirs.append(dest_dir)

            for f in filenames:
                if len(destbase) == 0:
                    dest_path = os.path.expanduser(os.path.join("~", '.' + f))
                else:
                    dest_path = os.path.expanduser(os.path.join("~", "." + destbase, f))

                src_file = path.join(root, f)

                files_conflict_resolve(src_file, dest_path, renames, removes, installs )
            pass
        pass

    if dot_install:
        executes.append(dot_install)

    return (removes, renames, dirs, installs, executes)

def do_all_actions(removes, renames, dirs, installs, executes):
    print "Verification:"
    print "Will remove:"
    for f in removes:
        print "\t", f
    print ""
    print "Will Rename:"
    for s,d in renames:
        print "\t", s, "->", d
    print ""
    print "Will Create:"
    for d in dirs:
        print "\t", d
    print ""
    print "Will Install:"
    for s, d in installs:
        print "\t", s, "->", d
    print ""
    print "Will Execute:"
    for e in executes:
        print "\t", e
    print ""

    action = None
    while not(action in ['A', 'C']):
        print "(C)onfirm, (A)bort ?"
        action = sys.stdin.readline().strip()

    if action == 'A':
        return

    print "Removing ..."
    for r in removes:
        if path.isfile(r) or path.islink(r):
            os.remove(r)
        else:
            os.removedirs(r)

    print "Renaming ..."
    for s, d in renames:
        os.rename(s, d)

    print "Creating ..."
    for d in dirs:
        os.mkdir(d)

    print "Installing ..."
    for s, d in installs:
        os.symlink(s, os.path.abspath( d ))

    # dot path environment is the path for the dotfiles main tree, i.e. path for
    # current file
    dot_path = os.path.dirname(os.path.realpath(__file__))
    new_env = dict(os.environ)
    new_env['DOT_PATH'] = dot_path
    for e in executes:
        print "Executing ", e
        subprocess.call([os.path.abspath("./" + e)],
                        cwd=os.path.expanduser("~"),
                        env=new_env)
        print "-----"

def find_all_dots():
    dots = {}
    # dots maps name => (path, install, bundle)
    #     if path is set, a link is created on home
    #     if bundle is set, then every file inside bundle/name is linked to home and following paths
    #     if install is set, the program will be executed afterwards

    install_re = re.compile(r'^INSTALL_(?P<dot>[a-z0-9][a-z0-9\.\-]+)\.[a-z0-9]+$')

    for dot in os.listdir(DOT_DIR):
        if not(install_re.match(dot)):
            add_dot(dots, dot, dot, None, None, None)

    for dot in os.listdir(INSTALL_DIR):
        script = os.path.join(INSTALL_DIR, dot)
        add_dot(dots, dot, None, script, None, None)

    for dot in os.listdir(BUNDLEDIRS_DIR):
        add_dot(dots, dot, None, None, None, dot )

    for dot in os.listdir(BUNDLE_DIR):
        add_dot(dots, dot, None, None, dot, None )

    # Find all INSTALL_<dot> in all dirs
    for cur in [DOT_DIR, BUNDLE_DIR, INSTALL_DIR]:
        l = os.listdir(cur)
        for dot in l:
            match = install_re.match(dot)
            if match:
                script = os.path.join(cur, dot)
                add_dot(dots, match.groupdict()['dot'], None, script, None, None)
    return dots

def main():
    if len(sys.argv) == 1:
        action = 'help'
    elif sys.argv[1] == 'list':
        action = 'list'
    elif sys.argv[1] == 'install':
        action = 'install'
    else:
        action = 'help'

    if action == 'help':
        print '''\
              Usage:
                 install.py install [dot1 [dot2 [dot3 ...]]]
                 install.py list
        '''
        sys.exit(0)

    dots = find_all_dots()

    if action == 'list':
        print '\n'.join(dots.keys())
        sys.exit(0)

    # only action here is install
    if len(sys.argv) > 2:
        selection = sys.argv[2:]
    elif path.exists(SELECTION_FILE):
        selection = map(lambda l: l.strip(),
                        open(SELECTION_FILE).readlines())
    else:
        selection = dots.keys()

    print "Selected dots:", "\n".join(map(lambda i: " - " + i, selection))

    print ""

    removes = []
    renames = []
    dirs = []
    installs = []
    executes = []

    for dot in selection:
        print "Installing dot '%s'" % dot
        tup = dot_install(dot, *dots[dot])
        map(lambda t: t[0].extend(t[1]),
                zip([ removes, renames, dirs, installs, executes ],
                    tup))

        print "---------------------------------"

    do_all_actions(removes, renames, dirs, installs, executes)

if __name__ == "__main__": main()
