# Path to your oh-my-zsh installation.
export ZSH=${HOME}/.oh-my-zsh

# User machine local settings
export ZSH_USER_LOCAL="$HOME/.local/share/zsh/"
export ZSH_CUSTOM="$ZSH_USER_LOCAL/custom"

# Chase symlinks and avoid a lot of nonsense
setopt chaselinks


# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="avit"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(gitfast python sudo conda-zsh-completion tsuru autoswitch_conda)

# User configuration


# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [ -n "$SSH_CONNECTION" ]; then
   export EDITOR='emacsclient -t --alternate-editor="emacs" '
else
   export EDITOR='emacsclient -n -c --alternate-editor="emacs" '
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias e=$EDITOR

# Fix for emacs
if [[ "$TERM" == "dumb" ]]
then
    unsetopt zle
    unsetopt prompt_cr
    unsetopt prompt_subst
    unset precmd_functions
    unset preexec_functions
    PS1='$ '
fi

# custom user environment
if [ -f $HOME/.zprofile ] ; then
    source $HOME/.zprofile
fi

# global environment. Should just export variables
if [ -d ~/.local/etc/env.d/ ]; then
    for env_file in ~/.local/etc/env.d/* ; do
        source $env_file
    done
fi

# site configuration. Can be used to update plugins
# e.g. plugins+=(dnf systemd)
if [ -f ~/.local/share/zsh/site_conf.zsh ] ; then
    source ~/.local/share/zsh/site_conf.zsh
fi

# Shell setup
# These scripts are used to initialize interactive aspects of the shell
# and can execute more complex commands, redefine aliases, etc.
if [ -d ~/.local/etc/rc.d ]; then
    for rc in ~/.local/etc/rc.d/*; do
        source $rc
    done
fi


if [ -d "$HOME/.local/bin" ]; then
    export PATH="$HOME/.local/bin:$PATH"
fi

# if [ -f ${HOME}/.profile ]; then
#    source ${HOME}/.profile
# fi
export DISABLE_MAGIC_FUNCTIONS=true
source $ZSH/oh-my-zsh.sh
